name: Main

on:
  push:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Go benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run benchmark
        run: go test ./... -bench="Bench" -count 10 | tee output.txt

      - name: tree
        run: tree
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: cat
        run: cat output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmarks result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          go-version: '1.21'
      - name: Test with memory constraints
        run: systemd-run --scope -p MemoryMax=10M --user go test --parallel 1 ./...
      - uses: actions/upload-artifact@v4
        with:
          name: rpm-i386
          path: dist/warchaeology-*i386.rpm
          name: Benchmarks
          tool: 'go'
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-pages-branch: gh-pages
          auto-push: false
          fail-on-alert: true
          alert-threshold: "150%"


  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Detect snapshot
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.24.0
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # This should have been a matrix, but building separate targets is a paid feature in `goreleaser`
      - uses: actions/upload-artifact@v4
        with:
          name: darwin-x86_64
          path: dist/warchaeology_Darwin_x86_64*.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64
          path: dist/warchaeology_Linux_x86_64.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: linux-i386
          path: dist/warchaeology_Linux_i386.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64
          path: dist/warchaeology_Windows_x86_64.zip
      - uses: actions/upload-artifact@v4
        with:
          name: windows-i386
          path: dist/warchaeology_Windows_i386.zip
      - uses: actions/upload-artifact@v4
        with:
          name: deb-amd64
          path: dist/warchaeology_*amd64.deb
      - uses: actions/upload-artifact@v4
        with:
          name: deb-i386
          path: dist/warchaeology_*i386.deb
      - uses: actions/upload-artifact@v4
        with:
          name: rpm-x86_64
          path: dist/warchaeology-*x86_64.rpm
      - uses: actions/upload-artifact@v4
        with:
          name: rpm-i386
          path: dist/warchaeology-*i386.rpm

