name: Main

on:
  push:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Go benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run benchmark
        run: go test ./... -bench="Bench" -count 10 | tee output.txt

      - name: tree
        run: tree
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: cat
        run: cat output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmarks result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmarks
          tool: 'go'
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-pages-branch: gh-pages
          auto-push: false
          fail-on-alert: true
          alert-threshold: "150%"
