name: Main

on:
  push:

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: gobenchdata publish
        uses: bobheadxi/gobenchdata@v1
        with:
          PRUNE_COUNT: 0
          CHECKS: true
          PUBLISH_BRANCH: github-pages-test-branch
          PUBLISH: false
          BENCHMARKS_OUT: myBenchMarkResults.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
