# Do not run this workflow on pull request since this workflow has permission to modify contents.
name: Publish benchmarks

on:
  push:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  publish-benchmarks:
    name: Publish benchmark results
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Run benchmarks
        run: go test ./... -bench="Bench" -count 10 | tee benchmark-result.txt
      - name: Publish benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: benchmark-result.txt
          benchmark-data-dir-path: benchmarks/${{ matrix.os }}
          auto-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: true
          alert-threshold: "150%"

      - name: Create benchmark results json
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: benchmark-result.txt
          benchmark-data-dir-path: benchmarks/${{ matrix.os }}
          auto-push: false
          fail-on-alert: true
          alert-threshold: "150%"
      - name: tree
        run: tree
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: "Benchmark results for ${{ matrix.os }}"

          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: benchmark-results

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: 'benchmarks/**'
